spring:
  datasource:
    url: "jdbc:mysql://localhost/employee"
    username: "test"
    password: "test"
  jpa:
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:tc:mysql:5.6://hostname/databasename
  jpa:
    hibernate:
      ddl-auto: update